# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-gtr
dependencies:
  - python=3.8
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - opencv
  - pip:
    - torch==1.10
    - timm
    - lvis
    - lap
    - scipy
    - git+https://github.com/TAO-Dataset/tao
    # - -r file:requirements.txt