# To use:
#   $ conda env create -f environment.yml
#   $ conda activate <name>
name: machinelearnear-gtr
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - gh
  - pytorch=1.10
  - torchvision=0.11.1
  - opencv
  - pip:
    - timm
    - lvis
    - lap
    - scipy
    - git+https://github.com/TAO-Dataset/tao
    - "detectron2@git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2"
    # - -r file:requirements.txt